providers:
  - id: file://providers/promptfoo_provider.py

prompts:
  - "{{question}}"

tests:
  - vars:
      question: "cuál es el peso máximo"
  - vars:
      question: "Quiero agendar una cita para mañana a las 10"
